Refactor PR changes
- Remove -n option (name can be set with $AUDIOSOURCE_NAME).
- Export $ANDROID_SERIAL and remove adb $opts.
- Add contextual usage errors.

diff --git a/audiosource b/audiosource
--- a/audiosource
+++ b/audiosource
@@ -3,24 +3,14 @@
 set -eu
 
 AUDIOSOURCE_PROFILE=${AUDIOSOURCE_PROFILE:-debug}
-AUDIOSOURCE_DEFAULT_APK=app/build/outputs/apk/debug/app-debug.apk
 
 if [ "$AUDIOSOURCE_PROFILE" = 'release' ]; then
 	AUDIOSOURCE_DEFAULT_APK=app/build/outputs/apk/release/app-release.apk
+else
+	AUDIOSOURCE_DEFAULT_APK=app/build/outputs/apk/debug/app-debug.apk
 fi
 
 AUDIOSOURCE_APK=${AUDIOSOURCE_APK:-"$AUDIOSOURCE_DEFAULT_APK"}
-
-ANDROID_SERIAL=${ANDROID_SERIAL:-}
-while getopts ":s:" flag; do
-	case "$flag" in
-		s) ANDROID_SERIAL="$OPTARG" ;;
-	esac
-done
-shift $(( OPTIND - 1 ))
-
-[ -z ${ANDROID_SERIAL} ] && SERIAL_HASH= || SERIAL_HASH=-$(echo $ANDROID_SERIAL | sha256sum | cut -c 1-7)
-AUDIOSOURCE_NAME=android$SERIAL_HASH
 
 PYSOCAT="$(cat <<EOF
 import fcntl
@@ -75,26 +65,24 @@ build() {
 
 install() {
 	if ! command -v adb &> /dev/null; then
-		echo "error: adb not found"
+		echo "Error: adb not found"
 		exit 1
 	fi
 
 	if ! [ -f "$AUDIOSOURCE_APK" ]; then
-		echo "error: apk '$AUDIOSOURCE_APK' not found"
+		echo "Error: apk '$AUDIOSOURCE_APK' not found"
 		exit 1
 	fi
 
-	[ -z ${ANDROID_SERIAL} ] && opts= || opts="-s ${ANDROID_SERIAL}"
-
 	echo '[+] Waiting for device'
 
-	adb $opts wait-for-device
+	adb wait-for-device
 
 	echo '[+] Installing Audio Source'
 
-	adb $opts install -rtg "$AUDIOSOURCE_APK" || {
-		adb $opts uninstall fr.dzx.audiosource
-		adb $opts install -tg "$AUDIOSOURCE_APK"
+	adb install -rtg "$AUDIOSOURCE_APK" || {
+		adb uninstall fr.dzx.audiosource
+		adb install -tg "$AUDIOSOURCE_APK"
 	}
 }
 
@@ -117,7 +105,7 @@ _unload() {
 run() {
 	for cmd in adb pactl python3; do
 		if ! command -v $cmd &> /dev/null; then
-			echo "error: $cmd not found"
+			echo "Error: $cmd not found"
 			exit 1
 		fi
 	done
@@ -129,66 +117,83 @@ run() {
 
 	echo '[+] Loading PulseAudio module'
 
-	[ -z ${ANDROID_SERIAL} ] && opts= || opts="-s ${ANDROID_SERIAL}"
-
-	local OPTIND
-	while getopts ":n:" flag; do
-		case "$flag" in
-			n) AUDIOSOURCE_NAME="$OPTARG" ;;
-		esac
-	done
-	shift $(( OPTIND - 1 ))
-
 	pactl load-module module-pipe-source source_name="$AUDIOSOURCE_NAME" channels=1 format=s16 rate=44100 file="/tmp/$AUDIOSOURCE_NAME"
 
-	echo '[+] Waiting for device'
+	echo "[+] Waiting for device $ANDROID_SERIAL"
 
-	adb $opts wait-for-device
+	adb wait-for-device
 
 	echo '[+] Starting Audio Source'
 
-	adb $opts shell am start fr.dzx.audiosource/.MainActivity
+	adb shell am start fr.dzx.audiosource/.MainActivity
 
-	echo "[+] Forwarding audio to source: $AUDIOSOURCE_NAME"
+	echo "[+] Forwarding audio to $AUDIOSOURCE_NAME"
 
-	adb $opts forward localabstract:"$AUDIOSOURCE_NAME" localabstract:audiosource
+	adb forward localabstract:"$AUDIOSOURCE_NAME" localabstract:audiosource
 	sleep 1
 	python3 -c "$PYSOCAT" "$AUDIOSOURCE_NAME" "/tmp/$AUDIOSOURCE_NAME"
 }
 
 volume() {
-	pactl set-source-volume "$1" "$2"
+	if [ $# -eq 0 ]; then
+		echo 'Error: Missing volume level'
+		main_help
+		return 2
+	fi
+	pactl set-source-volume "$AUDIOSOURCE_NAME" "$1"
 }
 
 main_help() {
 	cat <<-EOF
-		Usage: ./audiosource [GLOBAL ARGS...] COMMAND [ARGS...]
+		Usage: ./audiosource [-s SERIAL] COMMAND [ARGS...]
 
-		Global Args:
+		Options:
 
 		   -s SERIAL  Use device with given serial (overrides \$ANDROID_SERIAL)
 
 		Commands:
 
-		   build              Build Audio Source APK (default: debug)
-		   install 	      Install Audio Source to Android device (default: debug)
-		   run [-n NAME]      Run Audio Source and start forwarding
-		   volume NAME LEVEL  Set volume to LEVEL (for example, 250%)
+		   build         Build Audio Source APK (default: debug)
+		   install       Install Audio Source to Android device (default: debug)
+		   run           Run Audio Source and start forwarding
+		   volume LEVEL  Set volume to LEVEL (for example, 250%)
 
 		Environment:
 
 		   AUDIOSOURCE_APK      APK path (default: app/build/outputs/apk/\$profile/app-\$profile.apk)
 		   AUDIOSOURCE_PROFILE  Build profile (debug or release, default: build)
-		   ANDROID_SERIAL	Serial number to connect to
+		   AUDIOSOURCE_NAME     Name of the PulseAudio source (default: android-<serial-hash>)
+		   ANDROID_SERIAL       Serial number to connect to (defaults to first ADB device)
 	EOF
 }
 
 main() {
+	local opt
+	local serial="${ANDROID_SERIAL:-}"
+
+	while getopts ":s:" opt; do
+		case "$opt" in
+			s)
+				serial="$OPTARG"
+				;;
+			*)
+				echo "Error: Invalid option '-$OPTARG' or missing argument"
+				main_help
+				return 2
+		esac
+	done
+
+	shift $((OPTIND-1))
+
+	export ANDROID_SERIAL="$serial"
+	AUDIOSOURCE_NAME="${AUDIOSOURCE_NAME:-"android-$(echo -n "$serial" | sha256sum | cut -c 1-7)"}"
+
 	if [ $# -eq 0 ]; then
+		echo 'Error: Missing command'
 		main_help
 		return 2
 	fi
-
+	
 	cmd="$1"
 	shift
 
@@ -197,6 +202,7 @@ main() {
 			"$cmd" "$@"
 			;;
 		*)
+			echo "Error: Invalid command '$cmd'"
 			main_help
 			return 2
 	esac
